export default {
    //ACTION TYPES
    FETCH_ALL_USERS: "FETCH_ALL_USERS",
    FETCH_USER_BY_ID: "FETCH_USER_BY_ID",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    DELETE_USER: "DELETE_USER",

    FETCH_ALL_PROJECTS: "FETCH_ALL_PROJECTS",
    FETCH_PROJECT_BY_ID: "FETCH_PROJECT_BY_ID",
    // CREATE_PROJECT: "CREATE_PROJECT",
    // DELETE_PROJECT: "DELETE_PROJECT",

    //REDUCERS TYPES
    USERS_REQUEST: "USERS_REQUEST",
    USERS_RESPONSE: "USERS_RESPONSE",
    ONE_USER_RESPONSE: "ONE_USER_RESPONSE",
    DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
    DELETE_USER_ERROR: "DELETE_USER_ERROR",
    USERS_ERROR: "USERS_ERROR",

    PROJECTS_REQUEST: "PROJECTS_REQUEST",
    PROJECTS_RESPONSE: "PROJECTS_RESPONSE",
    ONE_PROJECT_RESPONSE: "ONE_PROJECT_RESPONSE",
    PROJECTS_ERROR: "PROJECTS_ERROR",

    CURRENT_USER_REQUEST: "CURRENT_USER_REQUEST",
    CURRENT_USER_RESPONSE: "CURRENT_USER_RESPONSE",
    CURRENT_USER_ERROR: "CURRENT_USER_ERROR",
};
